### ISSUE TITLE
`toml` not installed with `pip install circup==1.5.0`

### ISSUE THREAD

**Issue by rsbohn** [adafruit/circup#191]
Installed the new release 1.5.0 but when I run `circup` it complains that `toml` is not installed.

Traceback (most recent call last):
  File "/home/venv/xxx/bin/circup", line 33, in <module>
    sys.exit(load_entry_point('circup==1.5.0', 'console_scripts', 'circup')())
  File "/home/venv/xxx/bin/circup", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/venv/xxx/lib64/python3.10/site-packages/circup/__init__.py", line 25, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

**Comment by rsbohn** [comment]
Here's the log of the `pip install`:

```shell
$ pip install circup
Collecting circup
  Downloading circup-1.5.0.tar.gz (100 kB)
     |████████████████████████████████| 100 kB 539 kB/s
  Preparing metadata (setup.py) ... done
Collecting semver~=3.0
  Downloading semver-3.0.2-py3-none-any.whl (17 kB)
Collecting Click>=8.0
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting appdirs>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting requests>=2.22.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting findimports>=2.1.0
  Downloading findimports-2.3.0-py2.py3-none-any.whl (26 kB)
Collecting update_checker
  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
     |████████████████████████████████| 104 kB 4.9 MB/s
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using legacy 'setup.py install' for circup, since package 'wheel' is not installed.
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, update-checker, semver, findimports, Click, appdirs, circup
    Running setup.py install for circup ... done
Successfully installed Click-8.1.7 appdirs-1.4.4 certifi-2023.7.22 charset-normalizer-3.3.2 circup-1.5.0 findimports-2.3.0 idna-3.4 requests-2.31.0 semver-3.0.2 update-checker-0.18.0 urllib3-2.1.0
```

**Comment by rsbohn** [comment]
Thanks!
