### ISSUE TITLE
Dependency issue when installing adafruit_nunchuk

### ISSUE THREAD

**Issue by hamslabs** [adafruit/circup#89]
I run 'circup install adafruit_nunchuk' on a blank QT Py and it doesn't install adafruit_bus_device. It returns
```
Found device at /media/ghampton/CIRCUITPY, running CircuitPython 6.1.0.
Searching for dependencies for: ['adafruit_nunchuk']
Ready to install: ['adafruit_nunchuk']

Installed 'adafruit_nunchuk'.
```

and the serial out on the QT Py shows
```
Traceback (most recent call last):
  File "code.py", line 6, in <module>
  File "adafruit_nunchuk.py", line 30, in <module>
ImportError: no module named 'adafruit_bus_device'

Code done running.
```

**Comment by Neradoc** [comment]
Ah the bundle's `requirements` directory is missing all the modules that are not directories.
